name: forgeedu-sync

on:
  push:
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Mirror to Forge
        uses: wearerequired/git-mirror-action@v1
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        with:
          source-repo: https://github.com/${{ github.repository }}.git
          destination-repo: https://oauth2:${{ secrets.GITLAB_TOKEN }}@forge.apps.education.fr/arnaudcolard/systeme_adduction_eau.git
